#!/usr/bin/env python3
"""
build.py — แปลง fw_policy_compare.html เป็น Cloudflare Worker (พร้อม Password Protection)
วิธีใช้:
  1. แก้ไข fw_policy_compare.html
  2. python3 build.py   (หรือ npm run deploy ซึ่งรัน wrangler deploy ตรงๆ)

รหัสผ่านเข้าเว็บ: ไม่ได้อยู่ในไฟล์นี้แล้ว (v3.7.0) — เก็บเป็น Cloudflare Secret
เพื่อให้ push โค้ดขึ้น GitHub ได้โดยไม่มีรหัสหลุดใน git history
  ตั้งรหัส  : npx wrangler secret put APP_PASSWORD
  เปลี่ยนรหัส: รันคำสั่งเดิมซ้ำ (มีผลทันที ไม่ต้อง deploy ใหม่)
  local dev : สร้างไฟล์ .dev.vars (ถูก .gitignore ไว้แล้ว) ใส่ APP_PASSWORD=...
"""
import json, os, sys

# หาไฟล์ HTML
HTML_FILE = 'fw_policy_compare.html'
if not os.path.exists(HTML_FILE):
    print(f"❌ ไม่พบ {HTML_FILE} — ต้องอยู่ใน folder เดียวกับ build.py")
    sys.exit(1)

with open(HTML_FILE, 'r', encoding='utf-8') as f:
    html = f.read()

# ---- Password protection settings ----
# รหัสผ่านอ่านจาก env.APP_PASSWORD ตอน runtime (Cloudflare Secret) — ห้าม hardcode ที่นี่
COOKIE_NAME = "fw_auth"
SESSION_SECONDS = 90 * 60  # หมดอายุ 90 นาทีหลังใส่รหัส ต้อง login ใหม่
# ค่า cookie ไม่ใช่รหัสผ่านตรงๆ แต่คำนวณจาก SHA-256(รหัสผ่าน + COOKIE_SALT) ตอน
# runtime — ทำให้มี secret ที่ต้องตั้งแค่ตัวเดียว และเปลี่ยนรหัสเมื่อไหร่ cookie เดิม
# ที่ค้างอยู่ทุกเครื่องจะใช้ไม่ได้ทันทีโดยอัตโนมัติ
COOKIE_SALT = "fw-migration-comparator-v1"

LOGIN_HTML = """<!DOCTYPE html>
<html lang="th">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>FW Migration Comparator — Login</title>
<style>
  body{font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:#0f172a;color:#e2e8f0;display:flex;align-items:center;justify-content:center;height:100vh;margin:0}
  .box{background:#1e293b;padding:40px;border-radius:12px;box-shadow:0 10px 30px rgba(0,0,0,.3);width:320px}
  h1{font-size:18px;margin:0 0 20px}
  input{width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid #334155;background:#0f172a;color:#e2e8f0;margin-bottom:14px;font-size:14px}
  button{width:100%;padding:10px;border:none;border-radius:8px;background:#2563eb;color:#fff;font-size:14px;cursor:pointer}
  button:hover{background:#1d4ed8}
  .err{color:#f87171;font-size:13px;margin:-6px 0 14px}
</style>
</head>
<body>
  <form class="box" method="POST" action="/login">
    <h1>🔒 FW Migration Comparator</h1>
    {error}
    <input type="password" name="password" placeholder="รหัสผ่าน" autofocus required>
    <button type="submit">เข้าสู่ระบบ</button>
  </form>
</body>
</html>"""

worker = f"""// FW Migration Comparator — Cloudflare Worker
// Auto-generated by build.py — DO NOT EDIT DIRECTLY
// Edit fw_policy_compare.html แล้วรัน: npm run deploy

const HTML = {json.dumps(html)};
const COOKIE_NAME = {json.dumps(COOKIE_NAME)};
const COOKIE_SALT = {json.dumps(COOKIE_SALT)};
const SESSION_SECONDS = {SESSION_SECONDS};
const LOGIN_HTML = {json.dumps(LOGIN_HTML)};

function loginPage(showError) {{
  const errHtml = showError ? '<div class="err">รหัสผ่านไม่ถูกต้อง</div>' : '';
  return LOGIN_HTML.replace('{{error}}', errHtml);
}}

// ค่า cookie = SHA-256(รหัสผ่าน + salt) คำนวณตอน runtime — ไม่มีรหัสผ่านและไม่มี
// token ค้างอยู่ในซอร์สโค้ดเลย จึง push ขึ้น GitHub ได้อย่างปลอดภัย
async function authToken(password) {{
  const buf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(password + '|' + COOKIE_SALT));
  return [...new Uint8Array(buf)].map(b => b.toString(16).padStart(2, '0')).join('');
}}

// เทียบแบบใช้เวลาคงที่ กัน timing attack (สตริงยาวเท่ากันเสมอเพราะเป็น hex hash)
function safeEq(a, b) {{
  if (a.length !== b.length) return false;
  let d = 0;
  for (let i = 0; i < a.length; i++) d |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return d === 0;
}}

async function isAuthed(request, password) {{
  const cookie = request.headers.get('Cookie') || '';
  const tok = await authToken(password);
  return cookie.split(';').some(c => {{
    const v = c.trim();
    return v.startsWith(COOKIE_NAME + '=') && safeEq(v.slice(COOKIE_NAME.length + 1), tok);
  }});
}}

export default {{
  async fetch(request, env, ctx) {{
    const url = new URL(request.url);

    if (url.pathname === '/health') {{
      return new Response(JSON.stringify({{ status: 'ok', configured: !!env.APP_PASSWORD }}), {{
        headers: {{ 'Content-Type': 'application/json' }}
      }});
    }}

    // กันเผลอ deploy แล้วเว็บเปิดโล่ง: ถ้ายังไม่ได้ตั้ง secret ให้ปิดตายพร้อมบอกวิธีตั้ง
    const PASSWORD = env.APP_PASSWORD;
    if (!PASSWORD) {{
      return new Response(
        '<h2>ยังไม่ได้ตั้งรหัสผ่าน</h2><p>รัน <code>npx wrangler secret put APP_PASSWORD</code> แล้วลองใหม่</p>',
        {{ status: 503, headers: {{ 'Content-Type': 'text/html; charset=utf-8' }} }}
      );
    }}

    if (url.pathname === '/login' && request.method === 'POST') {{
      const form = await request.formData();
      const pass = form.get('password') || '';
      if (safeEq(String(pass), PASSWORD)) {{
        return new Response(null, {{
          status: 302,
          headers: {{
            'Location': '/',
            'Set-Cookie': `${{COOKIE_NAME}}=${{await authToken(PASSWORD)}}; Path=/; Max-Age=${{SESSION_SECONDS}}; HttpOnly; Secure; SameSite=Lax`
          }}
        }});
      }}
      return new Response(loginPage(true), {{
        status: 401,
        headers: {{ 'Content-Type': 'text/html; charset=utf-8' }}
      }});
    }}

    if (url.pathname === '/logout') {{
      return new Response(null, {{
        status: 302,
        headers: {{
          'Location': '/',
          'Set-Cookie': `${{COOKIE_NAME}}=; Path=/; Max-Age=0`
        }}
      }});
    }}

    if (!(await isAuthed(request, PASSWORD))) {{
      return new Response(loginPage(false), {{
        status: 401,
        headers: {{ 'Content-Type': 'text/html; charset=utf-8' }}
      }});
    }}

    return new Response(HTML, {{
      headers: {{
        'Content-Type': 'text/html; charset=utf-8',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
      }}
    }});
  }}
}};
"""

os.makedirs('src', exist_ok=True)
with open('src/index.js', 'w', encoding='utf-8') as f:
    f.write(worker)

kb = len(worker) // 1024
print(f"✅ Built src/index.js — {kb} KB (limit: 1,024 KB)")
print("🔒 Password protection: อ่านจาก Cloudflare Secret 'APP_PASSWORD' ตอน runtime")
print("   ยังไม่เคยตั้ง? → npx wrangler secret put APP_PASSWORD")
